/**
 * ADK Agent Client — Communicates with the ADK API server via SSE.
 *
 * ADK API exposes:
 *   POST /run_sse — streams events (thought, function_call, function_response, model_turn)
 *   POST /apps/{app}/users/{user}/sessions/{session} — create session
 *   GET  /apps/{app}/users/{user}/sessions — list all sessions
 *   GET  /apps/{app}/users/{user}/sessions/{session} — get session with full event history
 *
 * This client provides both real SSE and a mock mode for offline development.
 */

const API_BASE = import.meta.env.VITE_API_BASE || '';
const APP_NAME = import.meta.env.VITE_APP_NAME || 'orchestrator';
const USER_ID = import.meta.env.VITE_USER_ID || 'user_web';

export { APP_NAME, USER_ID, API_BASE };

/* ─── Session Management ──────────────────────────────────────────── */

/**
 * Create a new session on the ADK backend.
 * POST /apps/{app}/users/{user}/sessions/{session}
 * @param {string} sessionId — UUID generated by the frontend
 * @returns {Promise<Object>} — session object from the server
 */
export async function createSession(sessionId) {
  const url = `${API_BASE}/apps/${APP_NAME}/users/${USER_ID}/sessions/${sessionId}`;
  const res = await fetch(url, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({}),
  });
  if (!res.ok) {
    throw new Error(`Failed to create session: HTTP ${res.status}`);
  }
  return res.json();
}

/**
 * Delete a session on the ADK backend.
 * DELETE /apps/{app}/users/{user}/sessions/{session}
 * @param {string} sessionId
 */
export async function deleteSession(sessionId) {
  const url = `${API_BASE}/apps/${APP_NAME}/users/${USER_ID}/sessions/${sessionId}`;
  const res = await fetch(url, {
    method: 'DELETE',
  });
  if (!res.ok) {
    throw new Error(`Failed to delete session: HTTP ${res.status}`);
  }
}

/**
 * List all sessions for the current user.
 * GET /apps/{app}/users/{user}/sessions
 * @returns {Promise<Array>} — array of session summaries (id, timestamps, etc.)
 */
export async function listSessions() {
  const url = `${API_BASE}/apps/${APP_NAME}/users/${USER_ID}/sessions`;
  const res = await fetch(url);
  if (!res.ok) {
    throw new Error(`Failed to list sessions: HTTP ${res.status}`);
  }
  return res.json();
}

/**
 * Get a session with full event/conversation history.
 * GET /apps/{app}/users/{user}/sessions/{session}
 * @param {string} sessionId
 * @returns {Promise<Object>} — session object with events array
 */
export async function getSession(sessionId) {
  const url = `${API_BASE}/apps/${APP_NAME}/users/${USER_ID}/sessions/${sessionId}`;
  const res = await fetch(url);
  if (!res.ok) {
    throw new Error(`Failed to get session: HTTP ${res.status}`);
  }
  return res.json();
}

/* ─── Event History → Messages Parser ─────────────────────────────── */

/**
 * Parse ADK session events array into our frontend message format.
 * ADK events have a structure with role, parts, etc.
 * @param {Array} events — from getSession().events
 * @returns {Array} — messages in our {id, role, content, thoughts, toolCalls, timestamp} format
 */
export function parseSessionEvents(events) {
  if (!events || !Array.isArray(events)) return [];

  const messages = [];
  let currentAssistantMsg = null;

  for (const event of events) {
    // ADK events wrap role/parts inside `event.content`:
    //   { author: "orchestrator", content: { role: "model", parts: [...] } }
    // Prefer content.role ("user" | "model") over author (agent name).
    const role = event.content?.role || event.role || event.author;
    const parts = event.content?.parts || event.parts || [];

    // ADK may return timestamp as a Unix epoch number
    let timestamp;
    if (typeof event.timestamp === 'number') {
      timestamp = new Date(event.timestamp * 1000).toISOString();
    } else {
      timestamp = event.timestamp || new Date().toISOString();
    }

    if (role === 'user') {
      // Flush any pending assistant message
      if (currentAssistantMsg) {
        messages.push(currentAssistantMsg);
        currentAssistantMsg = null;
      }

      // Extract user text
      const textParts = parts.filter((p) => p.text).map((p) => p.text);
      const text = textParts.join('');

      // Extract file references
      const fileParts = parts
        .filter((p) => p.inline_data)
        .map((p) => ({
          name: 'attachment',
          type: p.inline_data.mime_type,
          size: 0,
        }));

      if (text || fileParts.length > 0) {
        messages.push({
          id: event.id || `user_${messages.length}_${Date.now()}`,
          role: 'user',
          content: text,
          files: fileParts.length > 0 ? fileParts : undefined,
          timestamp,
          isStreaming: false,
        });
      }
    } else if (role === 'tool') {
      // Dedicated "tool" role for function responses
      for (const part of parts) {
        if (part.function_response && currentAssistantMsg) {
          const name = part.function_response.name;
          const tc = currentAssistantMsg.toolCalls.find(
            (t) => t.name === name && t.result === null
          );
          if (tc) {
            tc.result = part.function_response.response || {};
          }
        }
      }
    } else {
      // Treat everything that is NOT "user" or "tool" as an assistant turn.
      // This covers role === "model", role === "assistant", and also
      // agent-name authors ("orchestrator", "search", "workspace", etc.)
      if (!currentAssistantMsg) {
        currentAssistantMsg = {
          id: event.id || `assistant_${messages.length}_${Date.now()}`,
          role: 'assistant',
          content: '',
          thoughts: [],
          toolCalls: [],
          timestamp,
          isStreaming: false,
        };
      }

      for (const part of parts) {
        if (part.thought && part.text) {
          // Thought/reasoning part
          currentAssistantMsg.thoughts.push(part.text);
        } else if (part.text) {
          // Regular text content
          currentAssistantMsg.content += part.text;
        } else if (part.function_call) {
          // Tool call
          currentAssistantMsg.toolCalls.push({
            id: part.function_call.id || part.function_call.name,
            name: part.function_call.name,
            args: part.function_call.args || {},
            status: 'complete',
            result: null,
          });
        } else if (part.function_response) {
          // Tool result — match back to the tool call
          const name = part.function_response.name;
          const tc = currentAssistantMsg.toolCalls.find(
            (t) => t.name === name && t.result === null
          );
          if (tc) {
            tc.result = part.function_response.response || {};
          } else {
            // Orphaned tool result, add as standalone
            currentAssistantMsg.toolCalls.push({
              id: part.function_response.id || name,
              name,
              args: {},
              status: 'complete',
              result: part.function_response.response || {},
            });
          }
        }
      }
    }
  }

  // Flush last assistant message
  if (currentAssistantMsg) {
    messages.push(currentAssistantMsg);
  }

  return messages;
}

/* ─── SSE Streaming ───────────────────────────────────────────────── */

/**
 * Send a message and stream the response via SSE.
 * @param {Object} params
 * @param {string} params.sessionId
 * @param {string} params.message — text content
 * @param {Array} params.files — optional file attachments [{name, mimeType, data}]
 * @param {Function} params.onThought — callback(text)
 * @param {Function} params.onToolCall — callback({name, args, id})
 * @param {Function} params.onToolResult — callback({id, name, result})
 * @param {Function} params.onText — callback(text, isFinal)
 * @param {Function} params.onError — callback(error)
 * @param {Function} params.onDone — callback()
 * @returns {Function} abort — call to cancel the stream
 */
export function streamMessage({
  sessionId,
  message,
  files = [],
  onThought,
  onToolCall,
  onToolResult,
  onText,
  onError,
  onDone,
}) {
  const controller = new AbortController();

  const parts = [];
  if (message) {
    parts.push({ text: message });
  }

  // Add file parts
  for (const file of files) {
    parts.push({
      inline_data: {
        mime_type: file.mimeType,
        data: file.data, // base64
      },
    });
  }

  const body = {
    app_name: APP_NAME,
    user_id: USER_ID,
    session_id: sessionId,
    new_message: {
      role: 'user',
      parts,
    },
    streaming: true,
  };

  fetch(`${API_BASE}/run_sse`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Accept: 'text/event-stream',
    },
    body: JSON.stringify(body),
    signal: controller.signal,
  })
    .then(async (response) => {
      if (!response.ok) {
        throw new Error(`HTTP ${response.status}: ${response.statusText}`);
      }

      const reader = response.body.getReader();
      const decoder = new TextDecoder();
      let buffer = '';

      while (true) {
        const { done, value } = await reader.read();
        if (done) break;

        buffer += decoder.decode(value, { stream: true });
        const lines = buffer.split('\n');
        buffer = lines.pop() || '';

        let currentEvent = '';

        for (const line of lines) {
          if (line.startsWith('event:')) {
            currentEvent = line.slice(6).trim();
          } else if (line.startsWith('data:')) {
            const rawData = line.slice(5).trim();
            if (!rawData) continue;

            try {
              const data = JSON.parse(rawData);
              handleEvent(currentEvent, data, {
                onThought,
                onToolCall,
                onToolResult,
                onText,
              });
            } catch {
              // Non-JSON data, treat as text
              if (currentEvent === 'model_turn' || !currentEvent) {
                onText?.(rawData, false);
              }
            }
          }
        }
      }

      onDone?.();
    })
    .catch((err) => {
      if (err.name === 'AbortError') return;
      onError?.(err);
    });

  return () => controller.abort();
}

function handleEvent(eventType, data, callbacks) {
  const { onThought, onToolCall, onToolResult, onText } = callbacks;

  switch (eventType) {
    case 'thought':
      onThought?.(data.text || data.content || JSON.stringify(data));
      break;

    case 'function_call': {
      const calls = extractToolCalls(data);
      calls.forEach((tc) => onToolCall?.(tc));
      break;
    }

    case 'function_response': {
      const results = extractToolResults(data);
      results.forEach((tr) => onToolResult?.(tr));
      break;
    }

    case 'model_turn':
    case 'content':
    default: {
      // Check for thought parts first
      const parts = data.parts || data.content?.parts || [];
      for (const part of parts) {
        if (part.thought && part.text) {
          onThought?.(part.text);
        } else if (part.function_call) {
          onToolCall?.({
            id: part.function_call.id || part.function_call.name,
            name: part.function_call.name,
            args: part.function_call.args || {},
          });
        } else if (part.function_response) {
          onToolResult?.({
            id: part.function_response.id || part.function_response.name,
            name: part.function_response.name,
            result: part.function_response.response || {},
          });
        }
      }

      const text = extractText(data);
      if (text) onText?.(text, false);
      break;
    }
  }
}

function extractText(data) {
  // ADK can send content in various structures
  if (typeof data === 'string') return data;
  if (data.text) return data.text;
  if (data.content?.parts) {
    return data.content.parts
      .filter((p) => p.text && !p.thought)
      .map((p) => p.text)
      .join('');
  }
  if (data.parts) {
    return data.parts
      .filter((p) => p.text && !p.thought)
      .map((p) => p.text)
      .join('');
  }
  return '';
}

function extractToolCalls(data) {
  const calls = [];
  const parts = data.parts || data.content?.parts || [];
  for (const part of parts) {
    if (part.function_call) {
      calls.push({
        id: part.function_call.id || part.function_call.name,
        name: part.function_call.name,
        args: part.function_call.args || {},
      });
    }
  }
  if (calls.length === 0 && data.name) {
    calls.push({
      id: data.id || data.name,
      name: data.name,
      args: data.args || {},
    });
  }
  return calls;
}

function extractToolResults(data) {
  const results = [];
  const parts = data.parts || data.content?.parts || [];
  for (const part of parts) {
    if (part.function_response) {
      results.push({
        id: part.function_response.id || part.function_response.name,
        name: part.function_response.name,
        result: part.function_response.response || {},
      });
    }
  }
  if (results.length === 0 && data.name) {
    results.push({
      id: data.id || data.name,
      name: data.name,
      result: data.response || data.result || {},
    });
  }
  return results;
}

/* ─── Mock Streamer (development without backend) ─────────────────── */

export function mockStreamMessage({
  message,
  onThought,
  onToolCall,
  onToolResult,
  onText,
  onDone,
}) {
  let cancelled = false;
  const delay = (ms) => new Promise((r) => setTimeout(r, ms));

  (async () => {
    await delay(300);
    if (cancelled) return;

    onThought?.('Analyzing the user request and determining the best approach...');
    await delay(800);
    if (cancelled) return;

    onThought?.(`The user asked: "${message}". Let me check if this requires Google Workspace actions or just a general response.`);
    await delay(600);
    if (cancelled) return;

    if (message.toLowerCase().includes('calendar') || message.toLowerCase().includes('schedule')) {
      onToolCall?.({
        id: 'call_1',
        name: 'calendar_list_events',
        args: { timeMin: '2026-04-07T00:00:00+05:30', timeMax: '2026-04-13T23:59:59+05:30' },
      });
      await delay(1200);
      if (cancelled) return;

      onToolResult?.({
        id: 'call_1',
        name: 'calendar_list_events',
        result: { events: [{ summary: 'Team Standup', start: '2026-04-07T10:00:00+05:30' }] },
      });
      await delay(400);
      if (cancelled) return;
    }

    if (message.toLowerCase().includes('email') || message.toLowerCase().includes('mail')) {
      onToolCall?.({
        id: 'call_2',
        name: 'gmail_search',
        args: { query: 'is:unread', maxResults: 5 },
      });
      await delay(1000);
      if (cancelled) return;

      onToolResult?.({
        id: 'call_2',
        name: 'gmail_search',
        result: { messages: [{ subject: 'Project Update', from: 'team@example.com' }] },
      });
      await delay(400);
      if (cancelled) return;
    }

    const response = getResponseForQuery(message);
    const words = response.split(' ');
    let accumulated = '';

    for (let i = 0; i < words.length; i++) {
      if (cancelled) return;
      accumulated += (i === 0 ? '' : ' ') + words[i];
      onText?.(accumulated, i === words.length - 1);
      await delay(30 + Math.random() * 40);
    }

    onDone?.();
  })();

  return () => {
    cancelled = true;
  };
}

function getResponseForQuery(query) {
  const q = query.toLowerCase();
  if (q.includes('calendar') || q.includes('schedule')) {
    return `Here's a summary of your upcoming week:\n\n## 📅 This Week\n\n| Day | Event | Time |\n|-----|-------|------|\n| Monday | Team Standup | 10:00 AM |\n| Monday | Design Review | 2:00 PM |\n| Tuesday | Sprint Planning | 11:00 AM |\n| Wednesday | 1:1 with Manager | 3:00 PM |\n| Thursday | DSA Study Block | 6:00 PM |\n| Friday | Team Retro | 4:00 PM |\n\nYou have **6 events** scheduled this week. Would you like me to:\n- Add a new event?\n- Reschedule anything?\n- Block focus time?`;
  }

  if (q.includes('email') || q.includes('mail')) {
    return `## 📧 Unread Emails\n\nYou have **3 unread emails**:\n\n1. **Project Update** from team@example.com\n   > Sprint velocity looks great this week. Details attached.\n\n2. **Meeting Notes** from manager@example.com\n   > Shared notes from yesterday's sync.\n\n3. **Invoice #2847** from billing@service.com\n   > Your monthly invoice is ready.\n\nWould you like me to draft a reply to any of these?`;
  }

  if (q.includes('task') || q.includes('todo')) {
    return `## ✅ Your Tasks\n\n### High Priority\n- [ ] Complete API integration\n- [ ] Review PR #142\n\n### Medium Priority\n- [ ] Update documentation\n- [ ] Prepare demo slides\n\n### Low Priority\n- [x] Fix linting warnings\n- [ ] Refactor auth module\n\nYou have **5 pending tasks**. Need me to add, update, or complete any?`;
  }

  return `I can help you manage your Google Workspace! Here's what I can do:\n\n### 📅 Calendar\n- View upcoming events\n- Schedule new meetings\n- Handle conflicts and reschedule\n\n### 📧 Gmail\n- Check unread emails\n- Draft and send replies\n- Search for specific messages\n\n### ✅ Tasks\n- View your task lists\n- Create and update tasks\n- Mark tasks as complete\n\n### 📄 Docs & Drive\n- Create documents\n- Search files\n- Share and organize\n\n\`\`\`javascript\n// Example: Ask me something like\n"Show my calendar for this week"\n"Draft a reply to the latest email"\n"Add a task to review the PR"\n\`\`\`\n\nWhat would you like to do?`;
}
